/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BigNumberish, BytesLike, utils } from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';

export type PromiseOrValue<T> = T | Promise<T>;

export interface LeveragerInterface extends utils.Interface {
  functions: {
    'MAX_REASONABLE_FEE()': FunctionFragment;
    'RATIO_DIVISOR()': FunctionFragment;
    'TWO_POW_16()': FunctionFragment;
    'feePercent()': FunctionFragment;
    'getConfiguration(address)': FunctionFragment;
    'getSupplyBorrowAmount(uint256,uint256,uint256,bool)': FunctionFragment;
    'getVDebtToken(address)': FunctionFragment;
    'initialize(address,address,uint256,address)': FunctionFragment;
    'loop(address,uint256,uint256,uint256,uint256,bool)': FunctionFragment;
    'loopETH(uint256,uint256,uint256)': FunctionFragment;
    'loopETHFromBorrow(uint256,uint256,uint256,uint256)': FunctionFragment;
    'ltv(address)': FunctionFragment;
    'owner()': FunctionFragment;
    'pool()': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'setFeePercent(uint256)': FunctionFragment;
    'setTreasury(address)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'treasury()': FunctionFragment;
    'weth()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'MAX_REASONABLE_FEE'
      | 'RATIO_DIVISOR'
      | 'TWO_POW_16'
      | 'feePercent'
      | 'getConfiguration'
      | 'getSupplyBorrowAmount'
      | 'getVDebtToken'
      | 'initialize'
      | 'loop'
      | 'loopETH'
      | 'loopETHFromBorrow'
      | 'ltv'
      | 'owner'
      | 'pool'
      | 'renounceOwnership'
      | 'setFeePercent'
      | 'setTreasury'
      | 'transferOwnership'
      | 'treasury'
      | 'weth'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'MAX_REASONABLE_FEE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'RATIO_DIVISOR', values?: undefined): string;
  encodeFunctionData(functionFragment: 'TWO_POW_16', values?: undefined): string;
  encodeFunctionData(functionFragment: 'feePercent', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'getConfiguration',
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: 'getSupplyBorrowAmount',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(functionFragment: 'getVDebtToken', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: 'loop',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: 'loopETH',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: 'loopETHFromBorrow',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: 'ltv', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pool', values?: undefined): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'setFeePercent',
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: 'setTreasury', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
  encodeFunctionData(functionFragment: 'weth', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'MAX_REASONABLE_FEE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'RATIO_DIVISOR', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'TWO_POW_16', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'feePercent', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getConfiguration', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getSupplyBorrowAmount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getVDebtToken', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'loop', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'loopETH', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'loopETHFromBorrow', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'ltv', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pool', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setFeePercent', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'weth', data: BytesLike): Result;

  events: {
    'FeePercentUpdated(uint256)': EventFragment;
    'Initialized(uint64)': EventFragment;
    'OwnershipTransferred(address,address)': EventFragment;
    'TreasuryUpdated(address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'FeePercentUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'TreasuryUpdated'): EventFragment;
}
